config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :avengers do
    resources :skills
  end
  resources :villains do
    resources :attacks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attack.rb
class Attack < ActiveRecord::Base
  belongs_to :villain
end

app/models/avenger.rb
class Avenger < ActiveRecord::Base
  validates :name, presence: true
  has_many :skills
end

app/models/skill.rb
class Skill < ApplicationRecord 

  belongs_to :avenger
end

app/models/villain.rb
class Villain < ActiveRecord::Base
  validates :name, presence: true
  has_many :attacks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/attacks_controller.rb
class AttacksController < ApplicationController

    def create
      @villain = Villain.find(params[:villain_id])
      @attack = @villain.attacks.create(params[:attack].permit(:attack))
      if @attack.save
        redirect_to villain_url(@villain)
      end
    end

    def destroy
      @villain=Villain.find(params[:villain_id])
      @attack=Attack.find(params[:id])
      @attack.destroy
      redirect_to villain_url(@villain)
    end
end

app/controllers/avengers_controller.rb
class AvengersController < ApplicationController
  # before_action :set_avenger, only: [:show, :edit, :update, :destroy]

  def index
    # render json: Avenger.all
    @avengers = Avenger.all
    # render "index.html.erb"
  end

  def show
    @avenger = Avenger.find(params[:id])
    # render "show.html.erb"
# ----NEW FOR SKILLS
    @skill = Skill.new
    @skills = @avenger.skills

  end




  def new
    @avenger = Avenger.new
  end

  def create
# Create action is invoked when the POST request was made by the browser
# due to the new.html.erb
  @avenger = Avenger.new(params[:avenger].permit(:name))
    if @avenger.save
      # render :show
      redirect_to avenger_url(@avenger)
    else
      render json: @avenger.errors.full_messages, status: :unprocessable_entity
    end
  end



  def edit
    @avenger = Avenger.find(params[:id])
  end

  def update
    @avenger = Avenger.find(params[:id])
    if @avenger.update(params[:hero].permit(:name))
      redirect_to avenger_url(@avenger)
    else
      render json: @avenger.errors.full_messages, status: :unprocessable_entity
    end
  end


  def destroy
    avenger = Avenger.find(params[:id])
    avenger.destroy
    redirect_to avengers_url
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def create
      @avenger = Avenger.find(params[:avenger_id])
      # :avenger_id is from the schema.rb
      @skill = @avenger.skills.create(skill_params)

      if @skill.save
        redirect_to avenger_url(@avenger)
      end
  end

  def destroy
    @avenger = Avenger.find(params[:avenger_id])

    @skill = Skill.find(params[:id])

    @skill.destroy

    redirect_to avenger_url(@avenger)
  end


  private
  def skill_params
    params.require(:skill).permit(:skill)
    # pointing at the schema.rb

  end
end

app/controllers/villains_controller.rb
class VillainsController < ApplicationController
  def index
    @villains = Villain.all
    # render "index.html.erb"
  end

  def show
    @villain = Villain.find(params[:id])
# ------NEW FOR ATTACKS
    @attack = Attack.new
    @attacks = @villain.attacks
  end

  def new
    @villain = Villain.new
  end

  def create
    @villain = Villain.new(params[:villain].permit(:name))
    if @villain.save
      redirect_to villain_url(@villain)
    else
      render json: @avenger.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    @villian = Villain.find(params[:id])
  end

  def update
    @villain = Villain.find(params[:id])
    if @villain.update(params[:villain].permit(:name))
      redirect_to villain_url(@villain)
    else
      render json: @avenger.errors.full_messages, status: :unprocessable_entity
    end

  end



  def destroy
    villain = Villain.find(params[:id])
    villain.destroy
    redirect_to villains_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attacks/_attack.html.erb
<% @attacks.each do |a| %>

  <li>
    <%= a.attack %>
    <%= link_to "Delete", villain_attack_path(a.villain_id, a.id), method: :delete %>
  </li>

<%end%>

app/views/attacks/_form.html.erb
<%= form_for ([@villain, @attack]) do |f| %>

  <%=f.label :Ability%>
  <%=f.text_field :attack%>

  <%=f.submit "Add Attack"%>
<%end%>

<%# this :attack here is pointing at the schema from migration %>

app/views/avengers/edit.html.erb
<h1>Edit Character</h1>

<form action="<%=avenger_url(@avenger)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">

  <label>Name:
    <input type="text" name="hero[name]">
    <button type="submit">Edit</button>
  </label>
</form>





<br>
<a href="<%=avenger_url%>">Back</a>
<br>
<a href="<%=avengers_url()%>">Team List</a>

app/views/avengers/index.html.erb
<h1>The Avengers!</h1>

<ul>
  <% @avengers.each do |avenger| %>
    <li>
      <a href="<%=avenger_url(avenger)%>"><%= avenger.name %></a>

<!-- ------------------Delete button -->
      <form action="<%= avenger_url(avenger) %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <button type="submit">Remove</button>
      </form>
    </li>
  <% end %>
</ul>


<a href="<%= new_avenger_url %>">New Member</a>
<br>
<a href="<%= villains_url %>">The Villains</a>

app/views/avengers/new.html.erb
<h1>Create New Avenger</h1>

<!-- <form action="/avengers" method="POST">
  <label>Name:
    <input type="text" name="avenger[name]">
    <button type="submit">Create</button>
  </label>
</form> -->


<!-- -----or above will work as well -->

<%= form_with model: @avenger do |f| %>

  <%=f.label :Name%>
  <%=f.text_field :name%>

  <%=f.submit "Create"%>
<%end%>


<br>
<a href="<%=avengers_url()%>">Team List</a>

app/views/avengers/show.html.erb
<h1><%= @avenger.name %></h1>

<h3>Power</h3>
<ul>
    <%= render 'skills/skill' %>
</ul>


<%= render 'skills/form'%>




<a href="<%=edit_avenger_url%>">Edit Page</a>
<br>
<a href="<%=avengers_url()%>">Team List</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/_form.html.erb
<%= form_for ([@avenger, @skill]) do |f| %>

  <%=f.label :Ability%>
  <%=f.text_field :skill%>

  <%=f.submit "Add Skill"%>
<%end%>

<%# this :skill here is pointing at the schema from migration %>

app/views/skills/_skill.html.erb
<% @skills.each do |c| %>

  <li>
    <%= c.skill %>
    <%= link_to "Delete", avenger_skill_path(c.avenger_id, c.id), method: :delete %>
  </li>

<%end%>

app/views/villains/edit.html.erb
<h1>Edit Page</h1>

<form action="<%=villain_url(@villain)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="text" name="villain[name]">
  <button type="submit">Edit</button>
</form>


<a href="<%=villain_url()%>">Back</a>

app/views/villains/index.html.erb
<h1>The Villains!</h1>

<ul>
  <% @villains.each do |villain|%>
  <li>
    <a href="<%=villain_url(villain)%>"><%= villain.name %></a>

    <form action="<%=villain_url(villain)%>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <button type="submit">Remove</button>
    </form>
  </li>
  <% end %>
</ul>



<a href="<%=new_villain_url%>">New Member</a>
<br>
<a href="<%=avengers_url%>">The Heroes</a>

app/views/villains/new.html.erb
<h1>New Addition</h1>

<form action="/villains" method="POST">
  <input type="text" name="villain[name]">
  <button type="submit">Create</button>
</form>

<a href="<%=villains_url%>">Villain List</a>

app/views/villains/show.html.erb
<h1><%=@villain.name%><h1>

  <h3>Power</h3>
  <ul>
    <%= render 'attacks/attack'%>
  </ul>

  <%= render 'attacks/form'%>



<a href="<%=edit_villain_url%>">Edit</a>
<br>
<a href="<%=villains_url%>">The Villains</a>